config/routes.rb
Rails.application.routes.draw do
  root :to => 'products#index'
  get "log_out" => "sessions#destroy", :as => "log_out" 
  
  resources :sessions, :only => [:new, :create, :destroy]

  resources :users, :only => [:new, :create, :show]

  resources :products do 
    resources :reviews, :only => [:show, :new, :create, :destroy]
  end 

end

app/models/product.rb
class Product < ActiveRecord::Base
	has_many :reviews, dependent: :destroy
	has_many :users, :through => :reviews

	belongs_to :user

	validates :description, :name, :presence => true
	validates :price_in_cents, :numericality => {:only_integer => true}
	 mount_uploader :image, AvatarUploader
	def formatted_price
		price_in_dollars = price_in_cents.to_f/ 100
		sprintf("%.2f", price_in_dollars)
	end

	def self.search(search)
		@products = Product.where('lower(name) = ?', search.downcase)
		
	end

	
end

app/models/review.rb
class Review < ActiveRecord::Base
	belongs_to :user
	belongs_to :product

	validates :comment, :presence => true
end

app/models/reviews.rb
class Reviews < ActiveRecord::Base
	belongs_to :user
	belongs_to :product
end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password

	has_many :reviews, dependent: :destroy
	has_many :products, :through => :reviews

	has_many :products, dependent: :destroy

	validates_presence_of :name, :email, :password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

def ensure_logged_in
	unless current_user
		flash[:alert] = "Please log in"
		redirect_to new_session_path
	end
end 
  private
  def current_user
  	@current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_filter :ensure_logged_in, :except => [:show, :index]

  def index
    # if params[:search]
    #   @products = Product.search(params[:search])

    #     if @products.size.zero?
    #   # :notice => "No results found"
    #       flash.now[:alert] = "No results found"
    #   # redirect_to pictures_url, :notice => "No results found"
    #       @products = Product.order('products.created_at DESC').page(params[:page])
    #     end

    # else

      @products = Product.order('products.created_at DESC').page(params[:page])

      respond_to do |format|
        format.html #allows the controller to respond to Javascript
        format.js
      end
    # end
  end

  def show
  	@product = Product.find(params[:id])

   
      @review = @product.reviews.build

  end

  def new
  	@product = Product.new
  end

  def edit
  	@product = Product.find(params[:id])
  end

  def create
  	@product = Product.new(product_params)
    @product.user_id =current_user.id
  	if @product.save
  		redirect_to @product
  	else
  		render :new
  	end 
  end 

  def update
  	@product = Product.find(params[:id])

  	if @product.update_attributes(products_params)
  		redirect_to products_path(@product)
  	else
  		render :edit
  	end
  end 

  def destroy
  	@product = Product.find(params[:id])
  	@product.destroy
  	redirect_to products_path
  end

  private
  def product_params
  	params.require(:product).permit(:name, :description, :price_in_cents, :image)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_filter :ensure_logged_in, :only => [:edit, :create, :show, :update, :destroy]
  before_filter :load_product

  def create
  	@review = @product.reviews.build(review_params)
  	@review.user_id = current_user.id

    respond_to do |format|
      if @review.save
        format.html {redirect_to product_path(@product.id), notice: 'Review created successfully.'}
        format.js {} #This will look for app/views/reviews/create.js.erb
      else 
       format.html{render 'products/show', alert: "There was an error."}
       format.js {} # This will look for app/views/reviews/create.js.erb
      end 
    end 
  end
  
  def show
    @review = Review.find(params[:id])
  end

  def destroy
  	@review = Review.destroy

  	@review.destroy
  end

  private
  def review_params
  	params.require(:review).permit(:comment, :product_id)
  end

  def load_product
  	@product = Product.find(params[:product_id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	user = User.find_by_email(params[:email])
  	if user && user.authenticate(params[:password])
  		session[:user_id]= user.id 
  		redirect_to products_url, :notice => "Logged in!"
  	else
  		flash.now[:alert]= "Invalid email or password"
  		render "new"
  	end

  end

  def destroy
  	session[:user_id]= nil
  	redirect_to products_url, :notice => "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  	@user = User.new
  end

  def create
  	@user = User.new(user_params) 
  	if 	@user.save
  		redirect_to products_url, :notice => "Signed up!"
  	else
  		render "new"
  	end
  end

  def show
    @user = User.find(params[:id])

    if current_user
      @my_products = @user.products
    end 
  end
  
  private
  def user_params
  	params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div data-alert class="alert-box info radius <%= name.to_s == 'notice' ? 'success' : 'alert' %>">
      <%= content_tag :div, msg %>
      <a href="#" class="close">&times;</a>
    </div>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Rainforest</title>
    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>
    <link href='http://fonts.googleapis.com/css?family=Muli|Maven+Pro:400,500|Nixie+One|Playball|' rel='stylesheet' type='text/css'>
    <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
      <nav class="top-bar logo-nav" data-topbar role="navigation" data-options="sticky_on: large">
        <ul class="title-area">
          <li class="name">
            <h1 id="app-logo"><%= link_to 'Rainforest', root_url %></h1>
          </li>
           <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
          <li class="toggle-topbar menu-icon"><a href="#"><span></span></a></li>
        </ul>
      </nav>

    <div class=" sticky">
      <nav class="top-bar nav-links" data-topbar role="navigation" data-options="sticky_on: large">
        <section class="top-bar-section">
          <!-- Right Nav Section -->
          <ul class="left left-nav">
            <% if current_user %>
              <li class="has-dropdown">
                <a href="#">Account</a>
                <ul class="dropdown">
                  <li><%= link_to "Add a product", new_product_path %></li>
                  <li><%= link_to 'Your products', user_path(current_user)%></li>
                  <li><a href="">Wish list</a></li>
                  <li><a href="">Help</a></li>
                </ul>
              </li>
              <li><%= link_to 'Log out',log_out_path %></li>
            <% else %>
              <li><%= link_to 'Log in', new_session_path %></li>
              <li><%= link_to 'Sign up', new_user_path %></li>
            <% end %>
          </ul>
          <ul class="right right-nav">
            <li class="has-form">
              <div class="row collapse">
                <div class="large-8 small-9 columns">
                   <%= text_field_tag :search, params[:search], :placeholder => 'Find stuff' %>
                </div>
                <div class="large-4 small-3 columns">
                  <a href="#" class="button [tiny small large] search-button"><i class="fa fa-search"></i></a>
                </div>
              </div>
            </li>
          </ul>
        </section>
      </nav>
    </div>


    <div class="row">
      <div class="large-8 large-centered columns">
        
        <%= render 'layouts/messages' %>
      </div>
    </div> 

    <%= yield %>
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/products/_form.html.erb
		<%= form_for(@product) do |f| %>

			<% if @product.errors.any? %>

				<div id="error_explanation">
					<h2>
						<%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:
					</h2>
					<ul>
						<% @product.errors.full_messages.each do |msg| %>
							<li><%= msg %></li>
						<% end %>
					</ul>
				</div>
			<% else %>
				<div class ="field">
					<%= f.label :name %><br />
					<%= f.text_field :name %>
				</div>

				<div>
					<%= f.label :description %><br />
					<%= f.text_area :description %>
				</div>

				<div>
					<%= f.label :price_in_cents %>
					<%= f.text_field :price_in_cents %>
				</div>

				<div>
					<%= f.label :image %>
					<%= f.file_field :image %>
				</div>


				<div class="actions text-center">
					<%= f.submit 'save', :class => 'button [tiny small large] form-button' %>
				</div>
			<% end %>
		<% end %>

app/views/products/_product.html.erb
      
      <%# @products.each do |product| %>
    
        <div class="large-4 small-6 columns">
          <figure>
            <div class="blur-img">
              <%= link_to image_tag(product.image), product_path(product.id), :class => 'index-image' %>
            </div>
            
            <figcaption>
              <p class='text-center'><%= link_to product.name, product_path(product.id)  %></p>
              <div class="price">
                $<%= product.formatted_price %>
              </div>
                <span class="subheader"><%= truncate(product.description, length: 40) %></span>
            </figcaption>
          </figure>
        </div>
      <%# end %>

app/views/products/_reviews.html.erb
 <%# @product.reviews.each do |review| %>
  <div class="review">
    <div class="poster">
    	<% if review.user != nil %>

        <p><strong>Posted by:</strong> <%= review.user.name %> <i>on</i> <%= review.created_at.strftime("%A, %B %d, %Y") %></p>
      <% end %>
    </div>
    <p class='comment'>
      <%= review.comment %><br>
    </p>
  </div>
  <%# end %>

app/views/products/edit.html.erb
<div class="row product-form-content">
	<div class="small-12 columns">

		<div class="row session-header">
			<div class="small-6 small-centered columns">
				<h1 class="text-center">Edit Product</h1>
			</div>
		</div>

		<div class="row">
			<div class="small-7 small-centered columns">

				<%= render 'form' %>
			</div>
		</div>
	</div>
</div>

app/views/products/index.html.erb
 	<div class="row">
    <div class="large-12 columns">

    	<div id="slider">
     		<ul class="example-orbit" data-orbit>
				  <li>
				    <%= image_tag 'rainforest-index-home.jpg'%>
				    <div class="orbit-caption text-center">
				      Find stuff for the home- appliances, decor and alot more.
				    </div>
				  </li>
				  <li class="active">
				    <%= image_tag 'rainforest-in-wo.jpg'%>
				    <div class="orbit-caption text-center">
				      Exercise gear and equiptment
				    </div>
				  </li>
				  <li>
				    <%= image_tag 'rainforest-index-mfash.jpg'%>
				    <div class="orbit-caption text-center">
				      Mens fashion.
				    </div>
				  </li>
				  <li>
				   <%= image_tag 'rainforest-index-fash.jpg'%>
				    <div class="orbit-caption text-center">
				      Women's Fashion.
				    </div>
				  </li>
				</ul>
    	</div>
    
    <hr/>
    </div>
  </div>
  
 
 
  <div class="row">
    <div class="large-4 columns">
      <%= image_tag 'rainforest-c1.jpg'%>
      <h4 class="content-section-header text-center">Latest trends</h4>
      <p class="content-section-text">Bacon ipsum dolor sit amet nulla ham qui sint exercitation eiusmod commodo, chuck duis velit. Aute in reprehenderit, dolore aliqua non est magna in labore pig pork biltong. Eiusmod swine spare ribs reprehenderit culpa. Boudin aliqua adipisicing rump corned beef.</p>
    </div>
    
    <div class="large-4 columns">
      <%= image_tag 'rainforest-c2.jpg'%>
      <h4 class="content-section-header text-center">Home Accesories</h4>
      <p class="content-section-text">Bacon ipsum dolor sit amet nulla ham qui sint exercitation eiusmod commodo, chuck duis velit. Aute in reprehenderit, dolore aliqua non est magna in labore pig pork biltong. Eiusmod swine spare ribs reprehenderit culpa. Boudin aliqua adipisicing rump corned beef.</p>
    </div>
    
    <div class="large-4 columns">
      <%= image_tag 'rainforest-c5.jpg'%>
      <h4 class="content-section-header text-center">Home Decor</h4>
      <p class="content-section-text">Bacon ipsum dolor sit amet nulla ham qui sint exercitation eiusmod commodo, chuck duis velit. Aute in reprehenderit, dolore aliqua non est magna in labore pig pork biltong. Eiusmod swine spare ribs reprehenderit culpa. Boudin aliqua adipisicing rump corned beef.</p>
    </div>
  
    </div>
   
 
   





<div class="row index-content">
	<div class="small-12 columns">

		<div class="row">
			<div class="small-6 small-centered columns index-header">		
				<h3 class="text-center">All Products</h3>
			</div>
		</div>

			
			<!-- renders a helpful message with numbers of displayed vs. total entries -->
			<div class="row">
				<div class="small-6 small-centered columns">
					<h4 class="text-center"><small><%= page_entries_info @products %></small></h4>
				</div>
			</div>

			<hr/>


		    <div id="products">
		    	<div class="row products-containers">
		      	<%= render :partial => 'product', :collection => @products %>
		      </div>
		    </div>


			<!-- outputs several pagination links such as « First ‹ Prev ... 2 3 4 5 6 7 8 9 10 ... Next › Last » -->
			<%= paginate @products %>
	</div>
</div>

app/views/products/index.js.erb
$('#products').append("<%= escape_javascript(render :partial => 'product', :collection => @products %>)");
$('.pagination').replaceWith("<%= j paginate(@products) %>");

app/views/products/new.html.erb
<div class="row product-form-content">
	<div class="small-12 columns">

		<div class="row session-header">
			<div class="small-6 small-centered columns">
				<h1 class="text-center">New Product</h1>
			</div>
		</div>
		
		<div class="row">
			<div class="small-7 small-centered columns">

				<%= render 'form' %>
			</div>
		</div>

	</div>
</div>

app/views/products/show.html.erb
<div class="row show-page-content">
  <div class="small-12 columns">
    
    <div class="row">
      <div class="small-12 small-centered columns">    
        <p class='text-center product-img-container'>
          <%= image_tag @product.image %>
        </p>
      </div>
    </div>
    <div class="row show-page-header">
      <div class="small-12 columns show-page-header">    
          <h4 class='text-center product-header'><%= @product.name %></h4>
      </div>
    </div>
<% if current_user %>
  <% if current_user.id == @product.user.id %>
    <div class="row product-links">
      <div class="small-12 small-centered columns">    
         <%= link_to "", edit_product_path(@product), :class => 'fa fa-pencil'%>
         <%= link_to '', @product, method: :delete, :class =>"fa fa-trash-o", data: {confirm: "Are you sure you want to delete your product?"}%>
      </div>
    </div>
  <% else%>
    <p></p>
  <% end %>
<% else %>
  <p></p>
<% end %>
    <div class="row product-info">
      <div class="small-12 columns">
        <p>
        	<strong>Description:</strong>
        	<%= @product.description %>
        </p>

        <p>
        	<strong>Price: $ </strong>
        	<%= @product.formatted_price %>
        </p> 
      </div>
    </div>

    <!-- so if the current user is true they should be able to see the form below to create a new review. -->
    <% if current_user %>
  <div class="row">
    <div class="small-12 columns">
      
    	<h3 class="text-center review-header">Reviews</h3>
    </div>
  </div>

    <div id="review-list">
      <%= render :partial => "reviews" %>
    </div>
    


      <%= form_for [@product, @review], :remote => true do |f| %>
        <% if @review.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>

            <ul>
            <% @review.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
            </ul>
          </div>
        <% end %>

        <div class="row new-review-form">
          <div class="small-12 large-9 medium-9 small-centered large-centered medium-centered columns">
              <div class="field">
                <%= f.label :new_comment, :class =>'comment-label' %>
                <%= f.text_area :comment, :placeholder => "write a new comment..." %>
              </div>
              <div class="actions">
                <%= f.submit 'Post', :class =>'button [tiny small large] form-button' %>
              </div>
          </div>
        </div>
      <% end %>

    <% else %>
      <p>Please <%= link_to "log in", new_session_path %> to add a review.</p> 
    <% end %>

app/views/products/show.js.erb
// $('body').append("<%= escape_javascript(render @product) %>");

app/views/reviews/create.html.erb
<h1>Reviews#create</h1>
<p>Find me in app/views/reviews/create.html.erb</p>

app/views/reviews/create.js.erb
$('#review-list').html("<%= escape_javascript(render(:partial => 'products/reviews')) %>");

app/views/reviews/destroy.html.erb
<h1>Reviews#destroy</h1>
<p>Find me in app/views/reviews/destroy.html.erb</p>

app/views/reviews/show.html.erb
<h1>Reviews#show</h1>
<p>Find me in app/views/reviews/show.html.erb</p>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<div class="row session-form-container">
	<div class="small-6 small-centered columns">

		<div class="row session-header">
			<div class="small-12 columns">
				
				<h1 class="text-center">Sign Up!</h1>
			</div>
		</div>

		<div class="row new-user-form">
			<div class="small-12 columns">
				<%= form_for @user do |f| %>
					<% if @user.errors.any? %>

					<div class="error_messages">
						<h2>Form is invalid</h2>
						<ul>
							<% for message in @user.errors.full_messages %>
							<li><%= message %></li>
							<% end %>
						</ul>
				<% end %>
					</div>

					 <div class="field">
				    <%= f.label :name %><br/>
				    <%= f.text_field :name %>
				  </div>
					<div class="field">
						<%= f.label :email %><br/>
						<%= f.text_field :email %>
					</div>
					<div class="field">
						<%= f.label :password %><br/>
						<%= f.password_field :password %> 
					</div>
					<div class="field">
						<%= f.label :password_confirmation %><br/>
						<%= f.password_field :password_confirmation %>
					</div>
					<div class="actions text-center">
						<%= f.submit 'Go', :class => 'button [tiny small large] form-button' %>
					</div>
				<% end %>
			</div>
		</div>
	</div>
</div>

app/views/users/show.html.erb
  <div class="row">      
    <div class="large-12 columns">
    	<!-- This is the code to disply the header -->
 

       <div class="row user-head-container">
        <div class="small-12 small-centered columns">
          <h3 class="text-center user-head">Your Products</h3>
        </div>
      </div>

<!-- This is the code to display the pictures -->

            <div class="panel user-images-panel">
              <div class="row">
                <% @my_products.each do |product| %>
                  <div class="large-4 small-6 columns">

                    <figure>
                      <div class="blur-img">
                        <%= link_to image_tag(product.image), "/products/#{product.id}", :class => 'index-image' %>
                      </div>
                      
                      <figcaption>
                          <h5 class='text-center'><%= product.name %></h5>
                          <span class="subheader"><%= truncate(product.description, length: 40) %></span>
                      </figcaption>
                    </figure>
                    
                  </div>
                <% end %>
              </div>
            </div>

<!-- outer most divs -->
  </div>
</div>  